from typing import TypedDict, List, Dict, Any, Optional

class Task(TypedDict):
    agent: str
    task: str

class EnterpriseState(TypedDict):
    # Inputs
    user_query: str
    user_id: Optional[str]
    session_id: Optional[str]
    
    # Metadata and Intent
    intent: Optional[str]
    
    # Tasks generated by Planner
    tasks: List[Task]
    
    # Tool Results
    sql_results: List[Dict[str, Any]]
    rag_results: List[Dict[str, Any]]
    tool_results: List[Dict[str, Any]]
    
    # Intermediate outputs
    agent_outputs: List[Dict[str, Any]]
    
    # Business Analyst outputs
    findings: Optional[str]
    recommendations: Optional[str]
    
    # Reflection / Loop control
    confidence: float
    need_replan: bool
    retry_count: int
    
    # Final response to user
    final_answer: str
